import Logo from "./assets/images/logo.png";
import Vector from "./assets/images/Vector.png";
import BannerPicture from "./assets/images/BannerPicture.png";
import trust from "./assets/images/trust.svg";
import vezarat from "./assets/images/vezarat.svg";
import sanat from "./assets/images/sanat.svg";
import  haf from "./assets/images/haf.svg";
import  hasin from "./assets/images/hasin.svg";
import  farabom from "./assets/images/farabom.svg";
import  rahsa from "./assets/images/rahsa.svg";
import  fanavaran from "./assets/images/fanavaran.svg";
import  pishkhan from "./assets/images/pishkhan.png";
 import mobile from "./assets/images/mobile.svg"
 import lock from "./assets/images/lock.svg"
import clock from "./assets/images/clock.svg"
import coines from "./assets/images/coines.svg"
import p1 from "./assets/images/p1.svg"
import p2 from "./assets/images/p2.svg"
import p3 from "./assets/images/p3.svg"
import p4 from "./assets/images/p4.svg"
import LowerBackGround from "./assets/images/LowerBackGround.png"
import product1 from "./assets/images/product1.svg"
import tell from "./assets/images/tell.svg"
import loc from "./assets/images/loc.svg"
import mail from "./assets/images/mail.svg"
import blogpic from "./assets/images/blogpic.svg"
import user from "./assets/images/user.svg"
export { Logo, Vector, BannerPicture, trust, vezarat, sanat,haf,hasin,farabom,rahsa,fanavaran,pishkhan,mobile,lock,clock,coines,p1,p2,p3,p4,LowerBackGround,product1,tell,loc,mail,blogpic,user};
